SapMachine #540: Various fixes and improvements to vitals
SapMachine #540: Various fixes and improvements to vitals

* Fix build error on gcc 5.4, Ubuntu 16.4
"stathist.cpp:885:63: error: enumeral and non-enumeral type in conditional expression [-Werror=extra]"

* Add safety measure to guard against suspected endless loop in printing code.

* Remove the take-sample-at-printing-time feature since it
could be dangerous and the output was confusing.

* Reduce default sample interval from 15 to 10 seconds.

* Add a new sub option, "max", to limit number of records printed.

* Add Vitals sampler thread to threads list output.

(cherry picked from commit ff04966519a91608129811c2aa94a0c14fe6a328)