8251414: Add test that invokeinterface of a protected method in java.lang.Object throws NoSuchMethodError Summary: Add the missing test cases to existing test InterfaceObjectTest.java Reviewed-by: lfoltan, coleenp